[workspace]
# Enable changelog updates
changelog_update = true
# Create git releases
git_release_enable = true
# Create git tags for releases
git_tag_enable = true
# Use semantic versioning
semver_check = true
